# Generated by Django 4.2.29 on 2026-04-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_item_category_remove_item_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='low_stock_threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
