# Generated by Django 4.2.29 on 2026-04-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_low_stock_threshold_item_status_item_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('borrow', 'Borrow'), ('return', 'Return')], max_length=10)),
                ('user_name', models.CharField(default='Anonymous', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.item')),
            ],
        ),
    ]
