# Generated by Django 4.2.29 on 2026-04-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_taskitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Equipment', 'Equipment'), ('Consumable', 'Consumable')], default='Equipment', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
    ]
