# Generated by Django 4.2.29 on 2026-04-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_category_alter_item_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskitem',
            old_name='quantity_requested',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Use', 'In Use'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
