# Generated by Django 4.2.29 on 2026-04-28 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('date_borrowed', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Returned', 'Returned')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='item',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(default='', help_text='QR or Barcode value', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Equipment', 'Equipment'), ('Consumable', 'Consumable'), ('Medical', 'Medical'), ('Safety', 'Safety'), ('Tools', 'Tools')], default='Equipment', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
        migrations.DeleteModel(
            name='EquipmentLog',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.item'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='core.item'),
        ),
    ]
