# Generated by Django 4.2.29 on 2026-04-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_borrowing_stocktransaction_remove_equipmentlog_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, help_text='DRRM-XXX-000', max_length=50, null=True, unique=True),
        ),
    ]
